//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_sangkien
    {
        public int id { get; set; }
        public Nullable<int> idSangKien { get; set; }
        public string danhSachCaNhanTapThe { get; set; }
        public Nullable<double> tienThuong { get; set; }
        public Nullable<int> daXoa { get; set; }
        public Nullable<int> loaiSangKien { get; set; }
        public Nullable<System.DateTime> ngaySangKien { get; set; }
        public Nullable<int> bophan { get; set; }
        public string soQuyetDinh { get; set; }
    }
}
